### ISSUE TITLE
Clicking outside of the Sidebar 

### ISSUE THREAD

**Issue by jared201** [jared201/beef#18]
Clicking outside of the sidebar should close the sidebar if it's open

**Comment by Weave-Trix** [comment]
Hi, can I help you with this?

**Comment by Weave-Trix** [comment]
Hi can i help you with this? @jared201

**Comment by jared201** [comment]
> Hi can i help you with this? @jared201

@Weave-Trix ok.

**Comment by Weave-Trix** [comment]
Please have a look at the pull request that I've made. Happy coding 👍

**Comment by jared201** [comment]
> Please have a look at the pull request that I've made. Happy coding 👍 @jared201

will do. thanks!
